### ISSUE TITLE
不能发起

### ISSUE THREAD

**Issue by grzrt** [littleredhat1997/CrowdFunding#1]
合约部署之后，怎么发布不了众筹。我在geth客户发起也不行，是怎么回事？

**Comment by zhangbincheng1997** [comment]
你确定修改了src/main/resources/config.properties里的相关数据吗？
钱包密码 password
钱包路径 path
合约地址 crowdfundingAddr

**Comment by grzrt** [comment]
都改了。我在Geth JavaScript console发起调用raiseFund方法 也不行， 我安装的geth有问题吗？

**Comment by grzrt** [comment]
可以。合约里的修改类的操作，需要调用contract.方法.sendTransaction(参数，{})。 刚研究明白。  thank you

**Comment by zhangbincheng1997** [comment]
哦哦，好的......不过我的代码是好久之前了，现在web3j已经更新很多版本了。另外当时代码很多地方都写得不好，见谅！

**Comment by grzrt** [comment]
是呀，更新版本挺大的。你现在从事区块链方面的工作吗？

**Comment by zhangbincheng1997** [comment]
不，我还是本科。学习区块链只是为了参加一个比赛。。。现在在学习机器学习深度学习。

**Comment by huanleyuan** [comment]
启动服务器 http://localhost:8080/crowdfunding/index.html
无法打开啊,"localhost 拒绝了我们的连接请求"
CrowdFundingMain运行时error:java.lang.RuntimeException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8545

**Comment by zhangbincheng1997** [comment]
@huanleyuan 你启动时候，打开 geth 了吗？或者你确定以太坊的端口正确吗？
