### ISSUE TITLE
404 – Not Found

### ISSUE THREAD

**Issue by huanleyuan** [littleredhat1997/CrowdFunding#2]
打开了geth钱包里部署了合约，config也配置了，
http://localhost:8080/ 可以打开，index.html右键浏览器打开会显示“众筹系统”页面。对应页面http://localhost:63342/crowdfunding/src/main/webapp/index.html?_ijt=je5sgcksg1b2dkgb7c5evj4o7
咋不是8080，对web不了解请指教。
但http://localhost:8080/crowdfunding/index.html 错误如下
（貌似路径不对，需要webcontent之类吗？ide是intellij,编译run都没有报错）

-----------------------------------------------------------------
HTTP Status 404 – Not Found
Type Status Report

Message /crowdfunding/index.html

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.5

**Comment by zhangbincheng1997** [comment]
@huanleyuan 是不是需要配置 tomcat 呢？在Run Configuration 那里看看。

**Comment by huanleyuan** [comment]
然 解决网址贴一下 https://www.cnblogs.com/xuange306/p/7012341.html
