### ISSUE TITLE
项目启动调用智能合约方法报错

### ISSUE THREAD

**Issue by 821318294** [littleredhat1997/CrowdFunding#4]
报错信息如下：
java.io.IOException: unexpected end of stream on Connection{localhost:8545, proxy=DIRECT hostAddress=localhost/0:0:0:0:0:0:0:1:8545 cipherSuite=none protocol=http/1.1}，请问下知道是什么原因嘛？

**Comment by zhangbincheng1997** [comment]
@821318294 我没有遇到这个情况，你有修改过代码吗？

**Comment by 821318294** [comment]
@littleredhat1997 没改过，是这在行抛出的异常
![image](https://user-images.githubusercontent.com/28640924/37579626-458d7cc6-2b7a-11e8-897c-f11bcd09188d.png)

**Comment by 821318294** [comment]
@littleredhat1997 配置文件里是只要改钱包密码、钱包路径和合约地址就行嘛，别的需要改么

**Comment by zhangbincheng1997** [comment]
@821318294 不需要改其他的，你截图的代码是？代码在工程哪一行出错的？

**Comment by 821318294** [comment]
![image](https://user-images.githubusercontent.com/28640924/37579904-e075c3fa-2b7b-11e8-9228-251c627b591b.png)
![image](https://user-images.githubusercontent.com/28640924/37579926-fa659506-2b7b-11e8-82fa-36c1ec8619a9.png)

调用send()的时候报错的

**Comment by 821318294** [comment]
我合约是通过geth部署的，在geth里调用合约方法没问题

**Comment by 821318294** [comment]
@littleredhat1997

**Comment by zhangbincheng1997** [comment]
@821318294 这个问题貌似是okhttp的问题？你可以先试试谷歌unexpected end of stream on Connection。。。我现在在上课，放学我在查查。

**Comment by 821318294** [comment]
@littleredhat1997 好的，麻烦了

**Comment by Howthemeaning** [comment]
@littleredhat1997 @821318294 老哥们，你们解决了吗

**Comment by Howthemeaning** [comment]
问题解决了，以-rpc --rpcaddr "127.0.0.1" 启动私有链
