### ISSUE TITLE
项目配置里这个文件没有的话运行不起来啊

### ISSUE THREAD

**Issue by gyz147** [littleredhat1997/CrowdFunding#7]
C:\\Users\\zhang\\AppData\\Roaming\\Ethereum\\keystore\\UTC--2020-06-09T13-05-38.565951700Z--8048300a95e800124db581b5f8e691e2f0f3bfdf

**Comment by zhangbincheng1997** [comment]
对，这个要自己部署以太坊，然后创建自己的钱包，具体看我另一个仓库 Ethereum
